-- Snowflake Data Warehouse setup: database, schemas, staging, and silver layer transformations

CREATE DATABASE FINAL_PROJECT;

CREATE SCHEMA FINAL_PROJECT.RAW;
CREATE SCHEMA FINAL_PROJECT.SILVER;
CREATE SCHEMA FINAL_PROJECT.GOLD;

USE DATABASE FINAL_PROJECT;
USE SCHEMA RAW;
CREATE STAGE POPULATION_STAGE;
SELECT * FINAL_PROJECT.RAW.POPULATION_STAGE;

LIST @POPULATION_STAGE;
SELECT COUNT(*) FROM RAW.economies;

CREATE OR REPLACE TABLE RAW.POPULATIONS (
    POP_ID NUMBER,
    COUNTRY_CODE STRING,
    YEAR NUMBER,    
    FERTILITY_RATE FLOAT,
    LIFE_EXPECTANCY FLOAT,
    SIZE NUMBER);

COPY INTO RAW.POPULATIONS
FROM @POPULATION_STAGE
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"');

SELECT COUNT(*) FROM RAW.POPULATIONS;

DESC TABLE RAW.economies;
