CREATE OR REPLACE TABLE SILVER_ECONOMIES_ENRICHED AS
SELECT
    e.*,
    p.SIZE AS POPULATION_SIZE,
    c.COUNTRY_NAME,
    c.CONTINENT,
    c.REGION
FROM RAW.ECONOMIES e
LEFT JOIN RAW.POPULATIONS p
    ON e.CODE = p.COUNTRY_CODE
    AND e.YEAR = p.YEAR
LEFT JOIN RAW.COUNTRIES c
    ON e.CODE = c.CODE;
    
SELECT *
FROM SILVER_ECONOMIES_ENRICHED
LIMIT 10;
