CREATE OR REPLACE PROCEDURE REFRESH_PIPELINE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    CREATE OR REPLACE TABLE SILVER.SILVER_ECONOMIES_ENRICHED AS
    SELECT
        e.*,
        p.SIZE AS POPULATION_SIZE,
        c.COUNTRY_NAME,
        c.CONTINENT,
        c.REGION
    FROM RAW.ECONOMIES e
    LEFT JOIN RAW.POPULATIONS p
        ON e.CODE = p.COUNTRY_CODE
        AND e.YEAR = p.YEAR
    LEFT JOIN RAW.COUNTRIES c
        ON e.CODE = c.CODE;

    CREATE OR REPLACE TABLE GOLD.GOLD_COUNTRY_COMPARISON AS
    SELECT
        COUNTRY_NAME,
        CONTINENT,
        REGION,

        MAX(CASE WHEN YEAR = 2010 THEN GDP_PERCAPITA END) AS GDP_2010,
        MAX(CASE WHEN YEAR = 2015 THEN GDP_PERCAPITA END) AS GDP_2015,

        MAX(CASE WHEN YEAR = 2015 THEN GDP_PERCAPITA END)
          - MAX(CASE WHEN YEAR = 2010 THEN GDP_PERCAPITA END) AS GDP_CHANGE,

        MAX(CASE WHEN YEAR = 2010 THEN POPULATION_SIZE END) AS POPULATION_2010,
        MAX(CASE WHEN YEAR = 2015 THEN POPULATION_SIZE END) AS POPULATION_2015,

        MAX(CASE WHEN YEAR = 2015 THEN POPULATION_SIZE END)
          - MAX(CASE WHEN YEAR = 2010 THEN POPULATION_SIZE END) AS POPULATION_CHANGE

    FROM SILVER.SILVER_ECONOMIES_ENRICHED
    WHERE YEAR IN (2010, 2015)
      AND COUNTRY_NAME IS NOT NULL
      AND COUNTRY_NAME IN (
        'Brazil',
        'Canada',
        'China',
        'Germany',
        'France',
        'United Kingdom',
        'India',
        'Japan',
        'Russian Federation'
      )
    GROUP BY
        COUNTRY_NAME,
        CONTINENT,
        REGION;

    RETURN 'Pipeline Refreshed Successfully';

END;
$$;

CALL REFRESH_PIPELINE();
